name: eslint_plugin
version: 0.0.1
language: nodejs
description: The pluggable linting utility for JavaScript and JSX.
tags:
 - eslint
 - plugin
 - nodejs
 - analyzer
 - format


public: true

# clone_in_docker: false

outputs:
  - name: FLOW_ESLINT_WARNING_COUNT
  - name: FLOW_ESLINT_ERROR_COUNT
  - name: FLOW_ESLINT_FILE_COUNT
  - name: FLOW_ESLINT_LOG_PATH

script_path: ./run.sh
